version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_ADDRESS}:${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "postgres",
          "-p",
          "${POSTGRES_PORT}",
          "-U",
          "${POSTGRES_USER}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  flyway:
    image: redgate/flyway:latest
    depends_on:
      postgres:
        condition: service_healthy
    command: -url=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB} -schemas=public -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate
    volumes:
      - ./migration:/flyway/sql

volumes:
  db_data:


