name: format-test
run-name: ${{ github.head_ref || github.ref_name }}-format-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  PROJECT_PATH: ./

jobs:
  check-code-format:
    name: Check code format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install gdformat
        run: |
          pip install gdtoolkit
        shell: bash
      - name: Check formatting in scenes and scripts directory
        run: |
          ./test/test-format.sh